openapi: 3.0.0
info:
  title: Ops Manager API for Mongod Process Management
  version: 1.0.0
  description: API documentation for managing mongod processes via the Ops Manager API.
paths:
  /groups/{projectId}/automationConfig:
    get:
      operationId: getAutomationConfig
      summary: Get Automation Configuration
      tags:
        - Automation Config
      parameters:
        - name: projectId
          in: path
          required: true
          description: The ID of the project for which to retrieve the automation configuration.
          schema:
            type: string
      responses:
        '200':
          description: Successful retrieval of the automation configuration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutomationConfig'
              examples:
                getResponse:
                  value: |
                    {
                      "lastRestart": "2023-07-13T17:45:00+05:30"
                    }
        '401':
          description: Unauthorized access.
        '500':
          description: Server error.
    put:
      operationId: updateAutomationConfig
      summary: Update Automation Configuration
      tags:
        - Automation Config
      parameters:
        - name: projectId
          in: path
          required: true
          description: The ID of the project for which to update the automation configuration.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AutomationConfig'
            examples:
              putRequest:
                value: |
                  {
                    "lastRestart": "2023-07-13T17:45:00+05:30"
                  }
      responses:
        '200':
          description: Successful update of the automation configuration.
        '401':
          description: Unauthorized access.
        '500':
          description: Server error.
components:
  schemas:
    AutomationConfig:
      type: object
      description: The automation configuration for a mongod process.
      properties:
        lastRestart:
          type: string
          format: date-time
          description: The timestamp for the last restart of the mongod process.
      required:
        - lastRestart
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
